# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1027, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1021, 611))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("/* ===== QTabWidget Dark Gray Style ===== */\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    background: #2b2b2b;\n"
"}\n"
"\n"
"/* شريط التابات */\n"
"QTabBar::tab {\n"
"    background: #3a3a3a;\n"
"    color: #cccccc;\n"
"    padding: 8px 16px;\n"
"    border: 1px solid #444;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 90px;\n"
"}\n"
"\n"
"/* عند المرور */\n"
"QTabBar::tab:hover {\n"
"    background: #4a4a4a;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* التاب المختار */\n"
"QTabBar::tab:selected {\n"
"    background: #1f1f1f;\n"
"    color: #ffffff;\n"
"    border-color: #666;\n"
"}\n"
"\n"
"/* التابات غير المختارة */\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"}\n"
"/* ===== Dark Red Border for QLabel ===== */\n"
"\n"
"QLabel {\n"
"    border: 2px solid #8b0000;   /* أحمر غامق */\n"
"    color: #ffffff;\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* خلفية الصفحة داخل التاب */\n"
"QWidget {\n"
"    background-color: #1f1f1f;\n"
"    color: #e0e0e0;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(240, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(660, 0, 208, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setStyleSheet("/* ===== Dark Red Button Style ===== */\n"
"\n"
"QPushButton {\n"
"    background-color: #8b0000;   /* أحمر غامق */\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* عند المرور */\n"
"QPushButton:hover {\n"
"    background-color: #a00000;\n"
"}\n"
"\n"
"/* عند الضغط */\n"
"QPushButton:pressed {\n"
"    background-color: #6f0000;\n"
"}\n"
"\n"
"/* عند التعطيل */\n"
"QPushButton:disabled {\n"
"    background-color: #3a3a3a;\n"
"    color: #9e9e9e;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setStyleSheet("/* ===== Dark Red Button Style ===== */\n"
"\n"
"QPushButton {\n"
"    background-color: #8b0000;   /* أحمر غامق */\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* عند المرور */\n"
"QPushButton:hover {\n"
"    background-color: #a00000;\n"
"}\n"
"\n"
"/* عند الضغط */\n"
"QPushButton:pressed {\n"
"    background-color: #6f0000;\n"
"}\n"
"\n"
"/* عند التعطيل */\n"
"QPushButton:disabled {\n"
"    background-color: #3a3a3a;\n"
"    color: #9e9e9e;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 151, 311))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(0, 350, 911, 200))
        self.frame_2.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(440, 0, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(180, 40, 461, 301))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(570, 0, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(340, 0, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(770, 70, 111, 31))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #8b0000;   /* أحمر غامق */\n"
"    background-image: url(:/icons/arrow-up.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* عند المرور */\n"
"QPushButton:hover {\n"
"    background-color: #a00000;\n"
"}\n"
"\n"
"/* عند الضغط */\n"
"QPushButton:pressed {\n"
"    background-color: #6f0000;\n"
"}\n"
"\n"
"/* عند التعطيل */\n"
"QPushButton:disabled {\n"
"    background-color: #3a3a3a;\n"
"    color: #9e9e9e;\n"
"}\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(640, 160, 111, 31))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #8b0000;   /* أحمر غامق */\n"
"    background-image: url(:/icons/arrow-left.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* عند المرور */\n"
"QPushButton:hover {\n"
"    background-color: #a00000;\n"
"}\n"
"\n"
"/* عند الضغط */\n"
"QPushButton:pressed {\n"
"    background-color: #6f0000;\n"
"}\n"
"\n"
"/* عند التعطيل */\n"
"QPushButton:disabled {\n"
"    background-color: #3a3a3a;\n"
"    color: #9e9e9e;\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(910, 160, 111, 31))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #8b0000;   /* أحمر غامق */\n"
"    background-image: url(:/icons/arrow-right.svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* عند المرور */\n"
"QPushButton:hover {\n"
"    background-color: #a00000;\n"
"}\n"
"\n"
"/* عند الضغط */\n"
"QPushButton:pressed {\n"
"    background-color: #6f0000;\n"
"}\n"
"\n"
"/* عند التعطيل */\n"
"QPushButton:disabled {\n"
"    background-color: #3a3a3a;\n"
"    color: #9e9e9e;\n"
"}\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(770, 250, 111, 31))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #8b0000;   /* أحمر غامق */\n"
"    background-image: url(:/icons/arrow-down (1).svg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* عند المرور */\n"
"QPushButton:hover {\n"
"    background-color: #a00000;\n"
"}\n"
"\n"
"/* عند الضغط */\n"
"QPushButton:pressed {\n"
"    background-color: #6f0000;\n"
"}\n"
"\n"
"/* عند التعطيل */\n"
"QPushButton:disabled {\n"
"    background-color: #3a3a3a;\n"
"    color: #9e9e9e;\n"
"}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(780, 160, 91, 41))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"     background-color: #8b0000;   /* أحمر غامق */\n"
"\n"
"    color: #00363a;\n"
"    border: none;\n"
"    padding: 8px 18px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #26c6da;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0097a7;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget.addTab(self.widget, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "task time:"))
        self.pushButton.setText(_translate("MainWindow", "start timer"))
        self.pushButton_2.setText(_translate("MainWindow", "reset timer"))
        self.label_5.setText(_translate("MainWindow", "campany name:"))
        self.label_4.setText(_translate("MainWindow", "pressure:"))
        self.label_6.setText(_translate("MainWindow", "depth:"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">mission time:60:00</p><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "mission time:"))
        self.label_10.setText(_translate("MainWindow", "60:00"))
        self.label_11.setText(_translate("MainWindow", "15:00"))
        self.pushButton_7.setText(_translate("MainWindow", "stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "main tab"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
